import hashlib
import hmac
import logging
from typing import Any, Dict, Optional
import razorpay

from app.core.config import settings
from app.core.exceptions import BadRequestException, InternalServerErrorException

logger = logging.getLogger(__name__)


class RazorpayService:
    """Service wrapper for Razorpay Payment Gateway integration."""

    def __init__(self) -> None:
        self._client: Optional[razorpay.Client] = None

    @property
    def key_id(self) -> str:
        return settings.RAZORPAY_KEY_ID

    @key_id.setter
    def key_id(self, value: str) -> None:
        settings.RAZORPAY_KEY_ID = value

    @property
    def key_secret(self) -> str:
        return settings.RAZORPAY_KEY_SECRET

    @key_secret.setter
    def key_secret(self, value: str) -> None:
        settings.RAZORPAY_KEY_SECRET = value

    @property
    def webhook_secret(self) -> str:
        return settings.RAZORPAY_WEBHOOK_SECRET

    @webhook_secret.setter
    def webhook_secret(self, value: str) -> None:
        settings.RAZORPAY_WEBHOOK_SECRET = value

    @property
    def client(self) -> razorpay.Client:
        if not self.key_id or not self.key_secret:
            raise BadRequestException("Razorpay API credentials (KEY_ID / KEY_SECRET) are not configured.")
        if self._client is None:
            self._client = razorpay.Client(auth=(self.key_id, self.key_secret))
        return self._client

    def create_order(
        self,
        amount_in_rupees: float,
        receipt: str,
        notes: Optional[Dict[str, Any]] = None,
        currency: str = "INR",
    ) -> Dict[str, Any]:
        """
        Creates a Razorpay Order.
        `amount_in_rupees`: total amount in INR (e.g. 250.50)
        Convert to paise: 25050 paise
        """
        if amount_in_rupees <= 0:
            raise BadRequestException("Invalid payment amount. Amount must be strictly positive.")

        amount_in_paise = int(round(amount_in_rupees * 100))
        data = {
            "amount": amount_in_paise,
            "currency": currency.upper(),
            "receipt": receipt,
            "notes": notes or {},
        }

        try:
            order = self.client.order.create(data=data)
            logger.info(f"Created Razorpay order ID {order.get('id')} for receipt {receipt}")
            return order
        except Exception as e:
            logger.error(f"Failed to create Razorpay order: {str(e)}", exc_info=True)
            raise InternalServerErrorException(f"Razorpay order creation failed: {str(e)}")

    def verify_payment_signature(
        self,
        razorpay_order_id: str,
        razorpay_payment_id: str,
        razorpay_signature: str,
    ) -> bool:
        """
        Verifies HMAC-SHA256 signature generated by Razorpay Checkout script.
        Formula: HMAC-SHA256(razorpay_order_id + "|" + razorpay_payment_id, secret)
        """
        if not razorpay_order_id or not razorpay_payment_id or not razorpay_signature:
            return False

        msg = f"{razorpay_order_id}|{razorpay_payment_id}"
        expected_signature = hmac.new(
            self.key_secret.encode("utf-8"),
            msg.encode("utf-8"),
            hashlib.sha256,
        ).hexdigest()

        is_valid = hmac.compare_digest(expected_signature, razorpay_signature)
        if not is_valid:
            logger.warning(
                f"Razorpay signature mismatch for order {razorpay_order_id}, payment {razorpay_payment_id}"
            )
        return is_valid

    def verify_webhook_signature(
        self,
        raw_body: bytes,
        signature: str,
        webhook_secret: Optional[str] = None,
    ) -> bool:
        """
        Verifies signature for incoming Razorpay Webhook notifications.
        Formula: HMAC-SHA256(raw_body, secret)
        """
        secret = webhook_secret or self.webhook_secret
        if not secret or not signature:
            logger.warning("Webhook secret or signature missing; skipping webhook verification.")
            return True  # If no secret configured, allow or handle per strictness

        expected_signature = hmac.new(
            secret.encode("utf-8"),
            raw_body,
            hashlib.sha256,
        ).hexdigest()

        return hmac.compare_digest(expected_signature, signature)

    def fetch_payment_details(self, payment_id: str) -> Dict[str, Any]:
        """Fetches payment status & details from Razorpay."""
        try:
            return self.client.payment.fetch(payment_id)
        except Exception as e:
            logger.error(f"Error fetching Razorpay payment {payment_id}: {str(e)}")
            raise BadRequestException(f"Could not fetch payment details: {str(e)}")

    def refund_payment(
        self,
        payment_id: str,
        amount_in_rupees: Optional[float] = None,
        notes: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """
        Initiates a full or partial refund for a Razorpay payment.
        """
        data: Dict[str, Any] = {}
        if amount_in_rupees is not None and amount_in_rupees > 0:
            data["amount"] = int(round(amount_in_rupees * 100))
        if notes:
            data["notes"] = notes

        try:
            refund = self.client.payment.refund(payment_id, data=data)
            logger.info(f"Initiated Razorpay refund for payment {payment_id}: refund ID {refund.get('id')}")
            return refund
        except Exception as e:
            logger.error(f"Failed to process Razorpay refund for payment {payment_id}: {str(e)}")
            raise BadRequestException(f"Razorpay refund failed: {str(e)}")



razorpay_service = RazorpayService()
